server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_join?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: noxknow
    password: 0618

  thymeleaf:
    cache: false

jwt:
  secret: "secretKey"